// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aqjcnnrijtivfcidrckr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFxamNubnJpanRpdmZjaWRyY2tyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMDE3MTAsImV4cCI6MjA2ODg3NzcxMH0.iL1p9zZZrM4zvzqwQ5IqTUIqY6_MbssSbvsIMACuLoQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});